<?php
/**
 * ManiyaTech
 *
 * @author        Milan Maniya
 * @package       ManiyaTech_CustomShippingRate
 */

use ManiyaTech\CustomShippingRate\Model\Carrier;

/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\Create\Shipping\Method\Form
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $block->getData('taxHelper');

$viewModel = $block->getViewModel();
$storeId = $block->getQuote()->getStore()->getStoreId();
$isVisibleAdmin = $viewModel->getConfigData('show_on_adminside', $storeId);
$shippingAddress = $block->getQuote()->getShippingAddress();
$shippingCountry = $shippingAddress ? $shippingAddress->getCountryId() : null;
$showCustomRate = $viewModel->isVisibleShippingInSelectedCountry($shippingCountry, $storeId);
$customShippingCode = Carrier::CODE;
$isVisibleCustomShipping = ($viewModel->isEnabled($storeId) && $isVisibleAdmin && $showCustomRate) ? true : false;
?>
<?php $_shippingRateGroups = $block->getShippingRates(); ?>
<?php if ($_shippingRateGroups): ?>
    <div id="order-shipping-method-choose" class="control">
        <dl class="admin__order-shipment-methods">
        <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
            <?php
            if (!$isVisibleCustomShipping && $code == $customShippingCode):
                continue;
                endif;
            ?>
            <dt class="admin__order-shipment-methods-title"><?= $escaper->escapeHtml($block->getCarrierName($code)) ?>
            </dt>
            <dd class="admin__order-shipment-methods-options">
                <ul class="admin__order-shipment-methods-options-list">
                <?php foreach ($_rates as $_rate): ?>
                    <?php $_radioProperty = 'name="order[shipping_method]" type="radio"' ?>
                    <?php $_code = $_rate->getCode() ?>
                    <li class="admin__field-option">
                        <?php if ($_rate->getErrorMessage()): ?>
                            <div class="messages">
                               <div class="message message-error error">
                                   <div><?= $escaper->escapeHtml($_rate->getErrorMessage()) ?></div>
                               </div>
                            </div>
                        <?php else: ?>
                            <?php $_checked = $block->isMethodActive($_code) ? 'checked="checked"' : '' ?>
                            <input <?= /* @noEscape */ $_radioProperty ?>
                                value="<?= $escaper->escapeHtmlAttr($_code) ?>"
                                id="s_method_<?= $escaper->escapeHtmlAttr($_code) ?>" <?= /* @noEscape */ $_checked ?>
                                class="admin__control-radio required-entry"/>
                            <label class="admin__field-label" for="s_method_<?= $escaper->escapeHtmlAttr($_code) ?>">
                                <?= $escaper->escapeHtml($_rate->getMethodTitle() ?
                                    $_rate->getMethodTitle() : $_rate->getMethodDescription()) ?> -
                                <strong>
                                    <?php $_excl = $block->getShippingPrice(
                                        $_rate->getPrice(),
                                        $taxHelper->displayShippingPriceIncludingTax()
                                    ); ?>
                                    <?php $_incl = $block->getShippingPrice($_rate->getPrice(), true); ?>

                                    <?= /* @noEscape */ $_excl ?>
                                    <?php if ($taxHelper->displayShippingBothPrices() && $_incl != $_excl): ?>
                                        (<?= $escaper->escapeHtml(__('Incl. Tax')) ?> <?= /* @noEscape */ $_incl ?>)
                                    <?php endif; ?>
                                </strong>
                            </label>
                            <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                                'onclick',
                                "order.setShippingMethod(this.value)",
                                'input#s_method_' . $escaper->escapeHtmlAttr($_code)
                            ) ?>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
                </ul>
            </dd>
            <?php endforeach; ?>

            <?php /*------- Start ManiyaTech Custom Shipping Rate --------*/ ?>
            <?php
            if ($isVisibleCustomShipping): ?>
                <dt class="admin__order-shipment-methods-title"><hr/></dt>
                <dd class="admin__order-shipment-methods-options" style="margin-top:10px;">
                    <ul class="admin__order-shipment-methods-options-list">
                        <li>
                            <p><strong><?=  $escaper->escapeHtml(__('CUSTOM SHIPPING RATE')); ?></strong></p>
                            <p><strong><?= $escaper->escapeHtml(__('Carrier/Rate:')); ?></strong>
                                <select id="custom-shipment-title" class="admin__control-select required-entry">
                                    <?php foreach ($viewModel->getShippingType($storeId) as $shippingType):?>
                                        <option value="<?= /* @noEscape */ $shippingType['code'] ?>" <?= $block->getActiveCustomShippingRateMethod() == $shippingType['code'] ? ' selected' : '' ?>><?php //phpcs:ignore ?>
                                            <?= /* @noEscape */ __($shippingType['title']); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                                <input id="custom-shipment-rate" type="text" style="width:75px; padding:3px;" placeholder="10.99" value="<?= /* @noEscape */ $block->getActiveCustomShippingRatePrice() ?>" class="input-text item-price required-entry" /><?php //phpcs:ignore ?>
                                <?= /* @noEscape */ $block->getButtonHtml(__('Set'), 'order.setShippingMethod(getCustomShippingCost())', 'scalable') ?><?php //phpcs:ignore ?>
                            </p>
                        </li>
                    </ul>
                    <ul class="messages" style="display:none;">
                        <li class="notice-msg"><?= /* @noEscape */ __('Note: This will override any shipping method selected above.'); ?></li><?php //phpcs:ignore ?>
                    </ul>
                </dd>
            <?php endif; ?>
            <?php /*------- End ManiyaTech Custom Shipping Rate --------*/ ?>

        </dl>
    </div>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display:none", 'div#order-shipping-method-choose') ?>
    <?php if ($_rate = $block->getActiveMethodRate()): ?>
        <div id="order-shipping-method-info" class="order-shipping-method-info">
            <dl class="admin__order-shipment-methods">
                <dt class="admin__order-shipment-methods-title">
                    <?= $escaper->escapeHtml($block->getCarrierName($_rate->getCarrier())) ?>
                </dt>
                <dd class="admin__order-shipment-methods-options">
                    <?= $escaper->escapeHtml($_rate->getMethodTitle() ?
                        $_rate->getMethodTitle() : $_rate->getMethodDescription()) ?> -
                    <strong>
                        <?php $_excl = $block->getShippingPrice(
                            $_rate->getPrice(),
                            $taxHelper->displayShippingPriceIncludingTax()
                        ); ?>
                        <?php $_incl = $block->getShippingPrice($_rate->getPrice(), true); ?>

                        <?= /* @noEscape */ $_excl ?>
                        <?php if ($taxHelper->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?= $escaper->escapeHtml(__('Incl. Tax')) ?> <?= /* @noEscape */ $_incl ?>)
                        <?php endif; ?>
                    </strong>
                </dd>
            </dl>
            <a href="#"
               class="action-default">
                <span><?= $escaper->escapeHtml(__('Click to change shipping method')) ?></span>
            </a>
        </div>
        <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
            'onclick',
            "$('order-shipping-method-info').hide();$('order-shipping-method-choose').show();event.preventDefault()",
            'div#order-shipping-method-info a.action-default'
        ) ?>
    <?php else: ?>
        <?php $scriptString = <<<script
require(['prototype'], function(){
    $('order-shipping-method-choose').show();
});
script;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    <?php endif; ?>
<?php elseif ($block->getIsRateRequest()): ?>
    <div class="order-shipping-method-summary">
        <strong class="order-shipping-method-not-available">
            <?= $escaper->escapeHtml(__('Sorry, no quotes are available for this order.')) ?>
        </strong>
    </div>
<?php else: ?>
    <div id="order-shipping-method-summary" class="order-shipping-method-summary">
        <a href="#" class="action-default">
            <span><?= $escaper->escapeHtml(__('Get shipping methods and rates')) ?></span>
        </a>
        <input type="hidden" name="order[has_shipping]" value="" class="required-entry" />
    </div>
    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
        'onclick',
        "order.loadShippingRates();event.preventDefault();",
        'div#order-shipping-method-summary a.action-default'
    ) ?>
<?php endif; ?>
<div id="shipping-method-overlay" class="order-methods-overlay">
    <span><?= $escaper->escapeHtml(__('You don\'t need to select a shipping method.')) ?></span>
</div>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div#shipping-method-overlay') ?>
<?php $scriptString = <<<script
    require(["Magento_Sales/order/create/form"], function(){

script;
$scriptString .= "order.overlay('shipping-method-overlay', " . ($block->getQuote()->isVirtual() ? 'false' : 'true') .
    ');' . PHP_EOL;
$scriptString .= "order.overlay('address-shipping-overlay', " . ($block->getQuote()->isVirtual() ? 'false' : 'true') .
 ');' . PHP_EOL;
$scriptString .= "order.isOnlyVirtualProduct = " . ($block->getQuote()->isVirtual() ? 'true' : 'false') . ';' . PHP_EOL;
$scriptString .= <<<script
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<?php /*------- Start ManiyaTech Custom Shipping Rate --------*/ ?>
<?php if ($isVisibleCustomShipping): ?>
    <?php $scriptString = <<<script
    function getCustomShippingCost(){
        var rate = $('custom-shipment-rate').value;
        var type  = $('custom-shipment-title')[$('custom-shipment-title').selectedIndex].value;
        var code = 'customshippingrate_' + type;
        var desc = '';

        return '{"rate" : "' + rate + '", "code" : "' 
        + code  + '", "type" : "' + type + '", "description" : "' + desc + '"}'; 
    }
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php endif; ?>
<?php /*------- End ManiyaTech Custom Shipping Rate --------*/ ?>
